### Numpy
Numpy is a fundamental library of scientific computing in python. It provides support for array and matrices, along with a collection of mathematical functions to operate on these data structures.

In [1]:
!pip install numpy

In [3]:
import numpy as np

In [6]:
# 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1, 5) # 1 row and 5 cols

array([[1, 2, 3, 4, 5]])

In [ ]:
# 2D array
arr2 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [12]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
# attributes of numpy array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of dimentions:", arr.ndim)
print("Size (number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size (in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimentions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [24]:
# Vectorization of numpy arrays
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element wise operations
print("Addition:", arr1 + arr2)
print("Substraction:", arr1 - arr2)
print("Multition:", arr1 * arr2)
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multition: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [28]:
# Universal functions
arr = np.array([2, 3, 4, 5, 6])

print("Square root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Sin:", np.sin(arr))
print("Log:", np.log(arr))

Square root: [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential: [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sin: [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Log: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [47]:
# Array slicing and indexing

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array:\n", arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [41]:
print(arr[0][0])
print(arr[0:2, 2:])
print(arr[1:, 1:3])

1
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


In [34]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [48]:
# Modify array elements
arr[0, 0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [49]:
arr[1:, 2:] = 50
print(arr)

[[100   2   3   4]
 [  5   6  50  50]
 [  9  10  50  50]]


In [50]:
# Statistical concept -- Normalization
# to have a mean of 0 and standard deviation of 1
data = np.array([1, 2, 3, 4, 5])

# Calcualte the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalized the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [51]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean = np.mean(data)
print("Mean:", mean)

median = np.median(data)
print("Median:", median)

std_dev = np.std(data)
print("Standard deviation:", std_dev)

variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard deviation: 2.8722813232690143
Variance: 8.25


In [60]:
# Logical Operations
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

data[(data >= 5) & (data <= 8)]

array([5, 6, 7, 8])